apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  labels:
    app: django-ecommerce
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 