version: "3.9"

services:
  web:
    build: .
    container_name: ecommerce_web
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ecommerce_db
      DATABASE_USER: alaa
      DATABASE_PASSWORD: 12345
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: alaa
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_volume:
