apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # يجب ترميز هذه القيم بـ Base64 (كما تم الاتفاق عليها مسبقاً)
  POSTGRES_DB: ZWNvbW1lcmNlX2Ri # ecommerce_db
  POSTGRES_USER: YWxhYQ==       # alaa
  POSTGRES_PASSWORD: MTIzNDU=     # 12345